version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clustered-data-warehouse-app
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/fx_deals_db"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "password"
    networks:
      - app-network
    volumes:
      - ./sample-data:/app/sample-data

  postgres:
    image: postgres:latest
    container_name: clustered-data-warehouse-db
    environment:
      POSTGRES_DB: fx_deals_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  postgres-data:
